describe('Smoketest', () => {

    beforeEach(() => {
        cy.visit('/')
    })

    it('Elementos de Encabezado', () => {
        cy.get('#loader > img').should('be.visible')
          .get('.hero--SubContent').should('be.visible')
          .get(':nth-child(1) > .infinitics-logo').should('be.visible')
          .get(':nth-child(1) > .rif').should('be.visible')
          .get('.hero--title > .text--green').should('be.visible')
          .get('.hero--title > .text--blue').should('be.visible')
          .get('.hero--text > :nth-child(3)').should('be.visible')
          .get(':nth-child(3)').should('be.visible')
          .get('#canvas3d').should('be.visible')
          .get('.hero--items-container > :nth-child(3)').click()
          .get('.hero--SubContent > .border-green').should('be.visible')
          .get('#measureButton').click()
          .get('.speedtest--mesage').should('be.visible')
          .get('#closeSpeedtest').should('be.visible').click()
          .get('.hero--SubContent .border-blue').scrollIntoView().should('not.be.visible')
    })

    it('Elementos de 2do fondo', () => {
        cy.get('#plans--section').scrollIntoView().should('be.visible')
          .get('.plans--plans-title > .text--green').should('be.visible')
          .get('.plans--plans-title > :nth-child(2)').should('be.visible')
          .get('.plans--plans-title > :nth-child(3)').should('be.visible')
          .get('.plans--plans-title > :nth-child(4)').should('be.visible')
          .get('.text--purple').should('be.visible')
          .get('.plans--extra-info-p').should('be.visible')
          .get('.plans--extra-info > .infinitics-logo').should('be.visible')
          .get('#plans--section > .border-white').should('be.visible')
          .get('#plans--section > .border-green').should('be.visible')
          .get('.plans--plans-title > .hero--items-container > .hero--item').should('be.visible')
          .get('#plans--man > img').scrollIntoView().should('be.visible')
          .get('#planesButton').should('be.visible').click()
          .get('#planesContainer').should('be.visible')
          .get(':nth-child(3) > .planes--plan--footer > .main--button > span').should('be.visible')
          .get('#closePlanes').should('be.visible').click()
    })

    it('Elementos de 3er fondo', () => {
        cy.get('.test--content-container').scrollIntoView().should('be.visible')
          .get('.test--title-container > :nth-child(1)').should('be.visible')
          .get('.test--title-container > .text--blue').should('be.visible')
          .get('.test--title-container > :nth-child(3)').should('be.visible')
          .get('.test--information > .text--white').should('be.visible')
          .get('#plans--section > .border-green').should('be.visible')
          .get('#canvas3dSpeedTest').scrollIntoView().should('be.visible')
          .get('.test--information > .main--button').should('be.visible')
    })

    it('Elementos de 4to fondo', () => {
        cy.get('#download--section').scrollIntoView().should('be.visible')
          .get('#test--section > .floating-circle--container').should('be.visible')
          .get('.download--buttons > .main--button').should('be.visible')
          .get('.download--buttons--storeButtons > :nth-child(1) > img').should('be.visible')
          .get('.download--buttons--storeButtons > :nth-child(2) > img').should('be.visible')
          .get('picture > img').scrollIntoView().should('be.visible')
          .get('.green--ring > .floating-circle').should('be.visible')
          .get('#download--section > .white--ring > .floating-circle').should('be.visible')
    })

    it('Elementos del footer', () => {
        cy.get('.footer--copyright').scrollIntoView().should('be.visible')
          .get('.footer--title-text > .text--green').should('be.visible')
          .get('#footer--blue--title').should('be.visible')
          .get('#footerLogo').should('be.visible')
          .get(':nth-child(2) > .rif').should('be.visible')
          .get('.footer--social-media').should('be.visible')
          .get('.footer--address').should('be.visible')
          .get('a.footer--download-button > img').should('be.visible')
          .get('div.footer--download-button > img').should('be.visible')
          .get('.footer-video').scrollIntoView().should('be.visible')
          .get('.footer--content').contains('RIF')
    })
})